### ISSUE TITLE
Cotoami Roadmap

### ISSUE THREAD

**Issue by marubinotto** [cotoami/cotoami#2]
* [x] Posting cotos as an anonymous user (no need to sign in)
* [x] Signing up and in (no need for passwords)
* [x] Saving anonymous cotos(posts) into the account when signing in
* [x] Deleting cotos
* [x] Cotonoma: grouping coto into cotonomas which are also posted as cotos in the timeline
* [x] Cotonoma members: sharing a conotoma with other amishis(users)
* [x] Cotonoma list: browsing the cotonomas posted in the current cotonoma
* [x] Cotonoma permalink
* [x] Chatting with other members in realtime
* [x] Organizing cotos into graph structures like oinker.me
* [x] Pin button in coto toolbar
* [x] Improve the UX of selecting and connecting cotos
* [x] "Post and connect" button 
* [x] Editing cotos
* [x] Editing cotonomas
* [x] Exporting cotos to a file in portable format
* [x] #60 Change the model of sharing content
* [x] Coto content summary
* [x] Converting a normal coto into a cotonoma
* [x] Treating cotonomas in the sidebar or pulldown list like cotos
* [x] Event pushing for pin/unpin/connect/disconnect 
* [x] Reordering pinned cotos
* [x] Reordering sub-cotos
* [x] Full-text search 
* [x] Graph Visualization
* [x] Collapsible columns
* [x] Unread Cotos Notification
* [ ] Reposting a coto/cotonoma to another cotonoma like [oinker's reoink](https://oinkerme.wordpress.com/2015/06/23/reoink-sharing-an-oink-graph-among-multiple-rooms/)
* [ ] Uploading images
* [ ] Browsing cotos/cotonomas by date 
* [ ] Connecting cotos by drag-and-drop

Under consideration:

* Markdown extension (ex. http://support.typora.io/Draw-Diagrams-With-Markdown/)

The concepts are inherited from:

* [Oinker.me](https://oinker.me/)
* [Piggydb](https://piggydb.net/)

**Comment by Gryphoenix** [comment]
Thumbs up! Not a coder but am very interested in this project. 👍

**Comment by Gryphoenix** [comment]
I could have missed this...are you planning on incorporating tagging?

**Comment by tjfwalker** [comment]
@Gryphoenix, I'm not a part of the project, I just recall coming across this (very) old post by @marubinotto regarding your question on tagging: [Tagging Turned Out to Be Not So Flexible](https://piggydb.net/2011/08/01/tagging-turned-out-to-be-not-so-flexible/)

**Comment by marubinotto** [comment]
Thank you @tjfwalker for the comment!

It is definitely what we are aiming for in this project.

With a reposting feature planned in the roadmap, you will be able to use cotonomas like tags (cotos can belong to multiple cotonomas), but they are more emergent or spontaneous, like "Tag as Concept" in [The Piggydb Way](https://piggydb.net/2012/06/20/the-piggydb-way-1-tag-as-concept-over-tag-as-index/).

**Comment by pihentagy** [comment]
Is there a way to rollup / fold long cotos? If you link 2 cotos, but the inner ones are long, it would be good...

**Comment by marubinotto** [comment]
I opened new issues for each unfinished task, so closed this issue.
